import dynamic from 'next/dynamic';
import Head from 'next/head';

const HomePage = dynamic(() => import('@/app/client/HomePage/Home'), {ssr: false});
export default function Home(props) {
  return (
    <>
      <Head>
        <title>Trang Chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='home-page'>
        <HomePage {...props}/>
      </div>
    </>
  )
}
