import dynamic from 'next/dynamic';
import Head from 'next/head';
import { Spin } from 'antd';
import { LoadingOutlined } from '@ant-design/icons';
const HomePage = dynamic(() => import('@/app/client/HomePage/Home'), {ssr: false});
export default function Home(props) {
  const {user, isLoading} = props;
  if (isLoading) {
    return <Spin size="large" indicator={<LoadingOutlined />} />
  } else {
    return (
      <>
        <Head>
          <title>Trang Chủ</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className='home-page'>
          <HomePage {...props}/>
        </div>
      </>
    )
  }
}
